// ---------------------------------------------------------------------------
// Asset URLs
// ---------------------------------------------------------------------------

/**
 * Base URL for externally hosted PMTiles assets (for example Cloudflare R2).
 * Leave null to load PMTiles from the local ./data directory.
 */
export const PMTILES_BASE_URL = "https://pub-6b5363ed35ff4c4b8842187caba576bb.r2.dev";

/** Same-origin data directory used for small JSON assets kept in the repo. */
const LOCAL_DATA_URL = "./data";

const PMTILES_URL_BASE = PMTILES_BASE_URL ?? LOCAL_DATA_URL;

/** PMTiles source for the overview point layer (zoom 0–10). */
export const POINTS_PMTILES_URL = `${PMTILES_URL_BASE}/glaciers_points.pmtiles`;

/** PMTiles source for the high-zoom polygon layer (zoom 10–13). */
export const POLYGONS_PMTILES_URL = `${PMTILES_URL_BASE}/glaciers_polygons.pmtiles`;

/** Lightweight JSON typeahead search index produced by build_pmtiles.py. */
export const SEARCH_INDEX_URL = `${LOCAL_DATA_URL}/search_index.json`;

/** Scenario definitions, year/area extents, field names. Generated by build_pmtiles.py. */
export const BUILD_METADATA_URL = `${LOCAL_DATA_URL}/build_metadata.json`;

// ---------------------------------------------------------------------------
// Layer names (must match tippecanoe --layer= values in build_pmtiles.py)
// ---------------------------------------------------------------------------

export const POINTS_SOURCE_LAYER = "points";
export const POLYGONS_SOURCE_LAYER = "polygons";

// ---------------------------------------------------------------------------
// Zoom thresholds
// ---------------------------------------------------------------------------

/** Below this zoom the point layer is shown; at or above it polygons are shown. */
export const DETAIL_POLYGON_ZOOM = 10;

// ---------------------------------------------------------------------------
// Sentinel values (must match build_pmtiles.py constants)
// ---------------------------------------------------------------------------

/** Integer stored in tile fields when a glacier survives through 2100 or data is missing. */
export const SURVIVES_SENTINEL = 9999;

/** Integer stored in tile fields when a glacier was already extinct before the current year. */
export const EXTINCT_SENTINEL = -1;

export const STUDY_HORIZON_YEAR = 2100;
export const CURRENT_YEAR = new Date().getFullYear();

// ---------------------------------------------------------------------------
// Color scheme
// ---------------------------------------------------------------------------

export const YEAR_STYLE = {
    alreadyExtinct: "#7f0000",
    /**
     * Six-stop continuous ramp: earliest (warm) → latest (cool/light).
     * Mapped linearly onto [yearExtent.min, yearExtent.max].
     */
    ramp: ["#c72e29", "#e3692e", "#f1a340", "#f9d27b", "#d7ecf6", "#92c5de"],
    survives: "#5aa9d6",
    missing: "#cbd5e1",
    outline: "#365266",
    hover: "#ffffff",
    selected: "#ffffff",
};

// ---------------------------------------------------------------------------
// Default scenario code (must match one emitted by the build script)
// ---------------------------------------------------------------------------

export const DEFAULT_SCENARIO_CODE = "27";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function formatScenarioLabel(code) {
    if (!/^\d+$/.test(code)) return code;
    const n = Number(code);
    // e.g. 15 → 1.5°C, 20 → 2.0°C, 27 → 2.7°C, 40 → 4.0°C
    return `${Math.floor(n / 10)}.${n % 10}\u00b0C warming`;
}

export function escapeHtml(value) {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}

export function formatNumber(value, digits = 2) {
    if (value === null || value === undefined || value === "") return "—";
    const n = Number(value);
    if (!Number.isFinite(n)) return escapeHtml(String(value));
    return n.toLocaleString(undefined, { maximumFractionDigits: digits });
}
